# Generated by Django 2.1.1 on 2018-09-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whorl', models.ImageField(upload_to='')),
                ('side_face', models.ImageField(upload_to='')),
                ('full_side', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorseOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.Horse')),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='horse_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.HorseOwner'),
        ),
    ]
