# Generated by Django 2.1 on 2018-09-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horseowner',
            old_name='user',
            new_name='user_id',
        ),
    ]
