# Generated by Django 2.1.2 on 2018-10-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbarqRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('start_stamp', models.DateField()),
                ('end_stamp', models.DateField()),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.Horse')),
            ],
        ),
    ]
