# Generated by Django 2.1.1 on 2018-10-06 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('event', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('additional', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AddReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='horse',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='horse',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='horse',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1700), django.core.validators.MinValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='addreminder',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.Horse'),
        ),
        migrations.AddField(
            model_name='addperformance',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.Horse'),
        ),
    ]
