# Generated by Django 2.1.2 on 2018-10-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0002_ebarqrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebarqrecord',
            name='end_stamp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ebarqrecord',
            name='start_stamp',
            field=models.DateField(null=True),
        ),
    ]
