# Generated by Django 2.1.1 on 2018-09-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0002_auto_20180919_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('horse_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('horse_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.HorseOwner')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBARQWebApp.Horse')),
            ],
        ),
    ]
