# Generated by Django 2.1 on 2018-10-06 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0002_addperformance_addreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='horse',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='horse',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1700), django.core.validators.MinValueValidator(150)]),
        ),
    ]
