# Generated by Django 2.1 on 2018-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0003_auto_20181018_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='height',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='weight',
        ),
        migrations.AlterField(
            model_name='horse',
            name='full_side',
            field=models.ImageField(blank=True, default='default1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='horse',
            name='side_face',
            field=models.ImageField(blank=True, default='default2.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='horse',
            name='whorl',
            field=models.ImageField(blank=True, default='default3.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='horseowner',
            name='display_image',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
    ]
