# Generated by Django 2.1.1 on 2018-09-22 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0003_horse_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='horse_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
