# Generated by Django 2.1 on 2018-10-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0004_auto_20181021_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreminder',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
