# Generated by Django 2.1 on 2018-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBARQWebApp', '0005_addreminder_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addperformance',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
